#!/usr/bin/env -S node --experimental-transform-types

import { parseArgs } from 'node:util'

const args = process.argv.slice(2);

args.forEach((arg, index) => {
    console.log(`Argument ${index}: ${arg}`);
});

